import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar
    nav_home: 'Home',
    nav_about: 'About',
    nav_strategy: 'Strategy',
    nav_portfolio: 'Portfolio',
    nav_team: 'Team',
    nav_pipeline: 'Pipeline',
    nav_insights: 'Insights',
    nav_investors: 'Investors',
    nav_contact: 'Contact',
    nav_fund: 'Fund',
    nav_inquire: 'Inquire Now',
    nav_inquire_full: 'Inquire About Investing',

    // Home
    home_hero_title: 'Simplex Capital',
    home_hero_subtitle: 'Unlocking the power of private markets',
    home_hero_desc: 'Driving technological development and competitiveness through strategic investments in high-growth tech companies.',
    home_explore_strategy: 'Explore Our Strategy',
    home_for_investors: 'For Investors',
    home_stats_fum: 'Funds Under Management',
    home_stats_aum: 'Assets Under Management',
    home_stats_exp: 'Years PE/VC Experience',
    home_stats_ipo: 'IPOs completed',
    home_stats_growth: 'Capitalization Growth',
    home_card_strategy_title: 'Investment Strategy',
    home_card_strategy_desc: 'Intelligent Automation · AI & Social Solutions · Platform Economy · Predictable Disruption · Digital Trust',
    home_card_portfolio_title: 'Portfolio Highlights',
    home_card_portfolio_desc: 'Proven exits including VK, Veeam, EPAM, Softline, and investments in emerging future unicorns.',
    home_card_team_title: 'Team Track Record',
    home_card_team_desc: '25+ years, 50+ IPOs across global stock exchanges.',
    home_learn_more: 'Learn More',
    home_pipeline_label: 'Investment Pipeline',
    home_pipeline_title: 'Up to $120M allocated at first close',
    home_pipeline_desc: 'Series C/D leaders in cybersecurity, enterprise software, data centers, and fintech – with allocation of first-close capital within one year into mature market-leading companies.',
    home_pipeline_btn: 'View Pipeline',
    home_quote: 'Technology investments significantly outperform all other asset classes, with 2025 US IPO market showing 347 total IPOs (+54% YoY) including 21 software and infrastructure listings.',
    home_quote_source: 'Source: PitchBook, 2025 Market Data',

    // Fund page
    fund_label: 'Fund Overview',
    fund_title: 'Tech Innovation and Development Fund',
    fund_desc: 'A premier institutional-grade vehicle targeting high-growth technology companies at inflection points.',
    fund_stat1_label: 'Target Gross Returns',
    fund_stat1_value: '~30% IRR or 3× Cash Multiple',
    fund_stat2_label: 'Launch Date',
    fund_stat2_value: '2027',
    fund_stat3_label: 'Fund Term',
    fund_stat3_value: '10 years + two 1-year extensions',
    fund_stat4_label: 'Fund Size',
    fund_stat4_value: '$300M, 1st closing $120M',
    fund_about_label: 'About the Fund',
    fund_about_title: 'Institutional-Grade Technology Investment',
    fund_about_desc: 'Simplex Capital\'s Tech Innovation and Development Fund is structured as a Limited Partnership targeting the most promising growth-stage technology companies across Russia and international markets. Our disciplined investment approach combines deep sector expertise with rigorous governance standards.',
    fund_features_governance: 'Institutional Governance',
    fund_features_governance_desc: 'Full LP/GP structure with independent auditors, advisory board, and transparent reporting.',
    fund_features_access: 'Exclusive Access',
    fund_features_access_desc: 'Proprietary deal flow from 25+ years of network relationships across global tech ecosystems.',
    fund_features_exits: 'Proven Exit Track Record',
    fund_features_exits_desc: '50+ IPO exits across London, New York, and Moscow stock exchanges with 10× average returns.',
    fund_structure_label: 'Fund Structure',
    fund_lp_title: 'Limited Partners (LPs)',
    fund_lp_desc: 'Institutional investors, DFIs, family offices, qualified private investors',
    fund_entity_desc: 'LP-GP Structure · Guernsey Jurisdiction · $300M Target',
    fund_portfolio_title: 'Portfolio Companies',
    fund_portfolio_desc: 'Series C/D tech leaders in cybersecurity, software, data centers',
    fund_structure_heading: 'Built for Institutional-Grade Investing',
    fund_structure_p1: 'The Simplex Capital Major International Fund brings together leading international and local financial institutions alongside qualified private investors to capitalize on the rapidly growing global technology sector.',
    fund_structure_p2: 'With a disciplined investment approach targeting Series C/D companies with clear 3-year IPO exit potential, the fund is structured to deliver superior risk-adjusted returns while providing LPs with robust governance, transparent reporting, and strategic value creation.',
    fund_structure_p3: 'Our GP commitment of 2% ensures strong alignment of interests, while our 2/20 fee structure with an 8% preferred return hurdle demonstrates our confidence in generating outsized performance.',
    fund_cta_title: 'Ready to Learn More?',
    fund_cta_desc: 'Contact our investor relations team to receive the full fund prospectus and schedule a discussion.',
    fund_cta_btn: 'Contact Investor Relations',

    // Strategy page
    strategy_label: 'Investment Strategy',
    strategy_title: "Tomorrow's Tech Leaders",
    strategy_desc: 'Our strategy targets high-growth technology companies at inflection points – Series C/D businesses with clear paths to IPO exits.',
    strategy_themes_label: 'Investment Themes',
    strategy_theme1_title: 'Intelligent Automation',
    strategy_theme1_desc: 'AI-driven process optimization and decision support systems transforming enterprise operations and industrial processes across sectors.',
    strategy_theme2_title: 'AI & Social Solutions',
    strategy_theme2_desc: 'Advanced machine learning platforms enhancing social connectivity, content delivery, and consumer engagement at scale.',
    strategy_theme3_title: 'Platform Economy',
    strategy_theme3_desc: 'Marketplace and sharing economy infrastructure enabling new business models and cross-border commerce.',
    strategy_theme4_title: 'Predictable Disruption',
    strategy_theme4_desc: 'Identifying and investing in technologies poised to reshape traditional industries within defined timeframes.',
    strategy_theme5_title: 'Digital Trust',
    strategy_theme5_desc: 'Cybersecurity, data privacy, and compliance solutions ensuring secure digital transformation for enterprises globally.',
    strategy_tech_label: 'Up to 70% of Fund',
    strategy_tech_title: 'Technologies & Business Models',
    strategy_markets_label: 'Up to 30% of Fund',
    strategy_markets_title: 'Markets on the Radar',
    strategy_deepdive_label: 'Strategy Deep Dive',
    strategy_exit_title: 'Exit Strategy & Timeline',
    strategy_exit_desc: 'Our primary exit strategy focuses on IPO listings across London, New York, and Moscow exchanges, leveraging our 50+ IPO track record. Secondary exits through strategic M&A are pursued when valuations exceed IPO alternatives. We target 3-year holding periods with clear milestones for each portfolio company.',
    strategy_selection_title: 'Selection Criteria',
    strategy_selection_desc: 'We seek companies with proven product-market fit, $10M+ revenue, 30%+ YoY growth, strong technical teams, and clear competitive moats. Our selection system combines quantitative scoring with deep sector expertise to identify leaders positioned for exponential growth.',
    strategy_risk_title: 'Risk Management',
    strategy_risk_desc: 'Portfolio diversification across sectors and geographies limits concentration risk. Active board participation, regular monitoring, and structured milestones ensure early identification and mitigation of downside scenarios.',
    strategy_value_title: 'Value Creation Approach',
    strategy_value_desc: 'Beyond capital, we provide operational support including go-global strategies, executive network access, legal and regulatory guidance, revenue optimization, and preparation for public market listings. Our "Smart Money" approach has driven 10× average capitalization growth across our track record.',

    // About
    about_label: 'About Us',
    about_title: 'Simplex Capital Major International Fund',
    about_desc: 'A premier institutional-grade vehicle for strategic technology investments across Russia and global markets.',
    about_fund_label: 'Fund Structure',
    about_fund_title: 'Built on Institutional Foundations',
    about_fund_desc: 'Structured as a Cayman Islands-domiciled Limited Partnership, our fund adheres to the highest standards of institutional governance and transparency.',
    about_spec_size: 'Target Fund Size',
    about_spec_term: 'Fund Term',
    about_spec_mgmt: 'Management Fee',
    about_spec_carry: 'Carried Interest',
    about_spec_return: 'Target Net Return',
    about_spec_hurdle: 'Hurdle Rate',

    // Portfolio
    portfolio_label: 'Portfolio',
    portfolio_title: 'Proven Track Record',
    portfolio_desc: 'A history of successful investments in high-growth technology companies across international markets.',

    portfolio_cat_social: 'Social / Platform',
    portfolio_cat_nano: 'Nanotechnology',
    portfolio_cat_it: 'IT Services',
    portfolio_cat_dist: 'IT Distribution',
    portfolio_cat_mobility: 'Mobility / On-Demand',
    portfolio_cat_telecom: 'Telecom / Digital',
    portfolio_cat_media: 'Media / Tech',
    portfolio_detail_vk: 'Largest social network in Russia/CIS with 100M+ monthly users. Multi-service digital ecosystem.',
    portfolio_detail_ocsia: 'Luxembourg-based nanotechnology company and the world\'s largest industrial producer of graphene nanotubes (single-walled carbon nanotubes).',
    portfolio_detail_epam: 'NYSE-listed. Global digital platform engineering and software development leader with $4B+ revenue.',
    portfolio_detail_softline: 'IPO on London Stock Exchange. Leading global IT solutions and services provider across 50+ countries.',
    portfolio_detail_dataart: 'Global technology consultancy with 6,000+ professionals. Board seat and 10× capitalization growth.',
    portfolio_detail_gett: 'Leading corporate transportation platform operating across major international markets.',
    portfolio_detail_mts: 'Russia\'s largest mobile operator with major digital ecosystem. NYSE and MOEX listed.',
    portfolio_detail_nmg: 'Russia\'s largest private media holding with extensive digital and broadcast operations.',
    portfolio_patterns_label: 'Key Patterns in Tech',
    portfolio_pattern1_title: 'Global First Mindset',
    portfolio_pattern1_desc: 'Russian tech founders increasingly build with global market ambitions from day one.',
    portfolio_pattern2_title: 'Strong Technical Background',
    portfolio_pattern2_desc: 'World-class engineering talent pool with deep expertise in AI, cybersecurity, and enterprise software.',
    portfolio_pattern3_title: 'Exceptional Teams & Efficient Business Models',
    portfolio_pattern3_desc: 'We partner with top-tier founding teams and prioritize operationally efficient, scalable business models, targeting growth investments with a clear, time-bound path to profitability.',

    // Team
    team_label: 'Team',
    team_title: 'Team Track Record',

    // Pipeline
    pipeline_label: 'Pipeline',
    pipeline_title: 'Investment Pipeline',
    pipeline_desc: 'Current opportunities under evaluation across our target sectors.',

    // Insights
    insights_label: 'Market Insights',
    insights_title: 'Technology Outperforms All Asset Classes',
    insights_desc: 'Data-driven analysis supporting our thesis that technology investments deliver superior risk-adjusted returns.',

    // For Investors
    investors_label: 'For Investors',
    investors_title: 'Investor Portal',
    investors_desc: 'Everything you need to evaluate and join the Simplex Capital Major International Fund.',

    // Contact
    contact_label: 'Contact',
    contact_title: 'Get In Touch',
    contact_desc: 'Reach out to our investor relations team to learn more about investing with Simplex Capital.',
    contact_name: 'Full Name',
    contact_email: 'Email Address',
    contact_phone: 'Phone Number',
    contact_type: 'Investor Type',
    contact_message: 'Message',
    contact_submit: 'Submit Inquiry',
    contact_success: 'Thank you for your inquiry. We will be in touch shortly.',

    // Footer
    footer_disclaimer: 'Past performance is not indicative of future results. Investments in private equity funds involve significant risk, including possible loss of principal. This website is for informational purposes only and does not constitute an offer to sell or solicitation of an offer to buy any securities.',
    footer_fund: 'Fund',
    footer_investors: 'Investors',
    footer_rights: 'All rights reserved.',
  },
  ru: {
    // Navbar
    nav_home: 'Главная',
    nav_about: 'О фонде',
    nav_strategy: 'Стратегия',
    nav_portfolio: 'Портфель',
    nav_team: 'Команда',
    nav_pipeline: 'Сделки',
    nav_insights: 'Аналитика',
    nav_investors: 'Инвесторам',
    nav_contact: 'Контакты',
    nav_fund: 'Фонд',
    nav_inquire: 'Связаться',
    nav_inquire_full: 'Запрос инвестора',

    // Home
    home_hero_title: 'Simplex Capital',
    home_hero_subtitle: 'Открываем возможности частных рынков',
    home_hero_desc: 'Содействуем технологическому развитию и конкурентоспособности через стратегические инвестиции в быстрорастущие технологические компании.',
    home_explore_strategy: 'Наша стратегия',
    home_for_investors: 'Инвесторам',
    home_stats_fum: 'Фонды под управлением',
    home_stats_aum: 'Активы под управлением',
    home_stats_exp: 'Лет опыта в PE/VC',
    home_stats_ipo: 'Проведено IPO',
    home_stats_growth: 'Средний рост капитализации',
    home_card_strategy_title: 'Инвестиционная стратегия',
    home_card_strategy_desc: 'Интеллектуальная автоматизация · ИИ и социальные решения · Платформенная экономика · Предсказуемые disruptions · Цифровое доверие',
    home_card_portfolio_title: 'Портфельные достижения',
    home_card_portfolio_desc: 'Успешные выходы: VK, Veeam, EPAM, Softline, а также инвестиции в компании — будущие единороги.',
    home_card_team_title: 'Опыт команды',
    home_card_team_desc: '25+ лет опыта, 50+ IPO на мировых фондовых биржах.',
    home_learn_more: 'Подробнее',
    home_pipeline_label: 'Инвестиционный пайплайн',
    home_pipeline_title: 'До $120M размещается при первом закрытии',
    home_pipeline_desc: 'Лидеры Series C/D в кибербезопасности, корпоративном ПО, ЦОД и финтехе — с размещением капитала первого закрытия в течение одного года в зрелые рыночно-лидирующие компании.',
    home_pipeline_btn: 'Смотреть сделки',
    home_quote: 'Технологические инвестиции значительно превосходят все другие классы активов: в 2025 году рынок IPO США зафиксировал 347 размещений (+54% г/г), включая 21 в сфере ПО и инфраструктуры.',
    home_quote_source: 'Источник: PitchBook, данные рынка 2025',

    // Fund page
    fund_label: 'Обзор фонда',
    fund_title: 'Фонд технологических инноваций и развития',
    fund_desc: 'Первоклассный институциональный инструмент, нацеленный на быстрорастущие технологические компании в точках перегиба.',
    fund_stat1_label: 'Целевая валовая доходность',
    fund_stat1_value: '~30% IRR или 3× денежный мультипликатор',
    fund_stat2_label: 'Дата запуска',
    fund_stat2_value: '2027',
    fund_stat3_label: 'Срок фонда',
    fund_stat3_value: '10 лет + два продления по 1 году',
    fund_stat4_label: 'Размер фонда',
    fund_stat4_value: '$300M, 1-е закрытие $120M',
    fund_about_label: 'О фонде',
    fund_about_title: 'Институциональные технологические инвестиции',
    fund_about_desc: 'Фонд технологических инноваций и развития Simplex Capital структурирован как партнёрство с ограниченной ответственностью (LP), нацеленное на наиболее перспективные технологические компании стадии роста на российском и международных рынках.',
    fund_features_governance: 'Институциональное управление',
    fund_features_governance_desc: 'Полная структура LP/GP с независимыми аудиторами, консультативным советом и прозрачной отчётностью.',
    fund_features_access: 'Эксклюзивный доступ',
    fund_features_access_desc: 'Проприетарный поток сделок из 25+ лет сетевых отношений в мировых технологических экосистемах.',
    fund_features_exits: 'Подтверждённая история выходов',
    fund_features_exits_desc: '50+ IPO-выходов на биржах Лондона, Нью-Йорка и Москвы со средней доходностью 10×.',
    fund_structure_label: 'Структура фонда',
    fund_lp_title: 'Ограниченные партнеры (LP)',
    fund_lp_desc: 'Институциональные инвесторы, институты развития (DFI), семейные офисы, квалифицированные частные инвесторы',
    fund_entity_desc: 'Структура LP-GP · Юрисдикция Гернси · Целевой объем: $300 млн',
    fund_portfolio_title: 'Портфельные компании',
    fund_portfolio_desc: 'Технологические лидеры на стадиях раундов C/D в сферах кибербезопасности, программного обеспечения и центров обработки данных',
    fund_structure_heading: 'Предназначен для инвестиций институционального уровня',
    fund_structure_p1: 'Фонд Simplex Capital Major International Fund объединяет ведущие международные и локальные финансовые институты вместе с квалифицированными частными инвесторами, чтобы реализовать потенциал стремительно растущего глобального технологического сектора.',
    fund_structure_p2: 'Благодаря дисциплинированному инвестиционному подходу, ориентированному на компании стадий C/D с ясными перспективами выхода через IPO в горизонте 3 лет, фонд структурирован таким образом, чтобы обеспечивать высокую риск-скорректированную доходность, одновременно предоставляя инвесторам (LP) надежную систему корпоративного управления, прозрачную отчетность и возможности для стратегического создания стоимости.',
    fund_structure_p3: 'Доля собственного участия генерального партнера (GP) в размере 2% гарантирует полное согласование интересов, а структура вознаграждения 2/20 с порогом предпочтительной доходности (hurdle rate) 8% демонстрирует нашу уверенность в достижении сверхвысоких показателей доходности.',
    fund_cta_title: 'Готовы узнать больше?',
    fund_cta_desc: 'Свяжитесь с нашей командой по работе с инвесторами, чтобы получить полный проспект фонда.',
    fund_cta_btn: 'Связаться с IR командой',

    // Strategy page
    strategy_label: 'Инвестиционная стратегия',
    strategy_title: 'Технологические лидеры завтрашнего дня',
    strategy_desc: 'Наша стратегия нацелена на быстрорастущие технологические компании в точках перегиба — бизнесы Series C/D с чёткими путями к IPO.',
    strategy_themes_label: 'Инвестиционные темы',
    strategy_theme1_title: 'Интеллектуальная автоматизация',
    strategy_theme1_desc: 'Оптимизация процессов на основе ИИ и системы поддержки принятия решений, трансформирующие корпоративные операции и промышленные процессы.',
    strategy_theme2_title: 'ИИ и социальные решения',
    strategy_theme2_desc: 'Платформы машинного обучения, повышающие социальную связанность, доставку контента и вовлечённость потребителей.',
    strategy_theme3_title: 'Платформенная экономика',
    strategy_theme3_desc: 'Инфраструктура маркетплейсов и экономики совместного потребления, обеспечивающая новые бизнес-модели и трансграничную торговлю.',
    strategy_theme4_title: 'Предсказуемые disruptions',
    strategy_theme4_desc: 'Выявление и инвестирование в технологии, готовые изменить традиционные отрасли в определённые сроки.',
    strategy_theme5_title: 'Цифровое доверие',
    strategy_theme5_desc: 'Решения в области кибербезопасности, защиты данных и соответствия требованиям для безопасной цифровой трансформации предприятий.',
    strategy_tech_label: 'До 70% фонда',
    strategy_tech_title: 'Технологии и бизнес-модели',
    strategy_markets_label: 'До 30% фонда',
    strategy_markets_title: 'Рынки в фокусе',
    strategy_deepdive_label: 'Детали стратегии',
    strategy_exit_title: 'Стратегия выхода и сроки',
    strategy_exit_desc: 'Основная стратегия выхода — IPO на биржах Лондона, Нью-Йорка и Москвы, опираясь на опыт 50+ IPO. Вторичные выходы через стратегические M&A реализуются, когда оценки превышают IPO-альтернативы. Целевой период удержания — 3 года.',
    strategy_selection_title: 'Критерии отбора',
    strategy_selection_desc: 'Мы ищем компании с подтверждённым соответствием продукта рынку, выручкой $10M+, ростом 30%+ г/г, сильными техническими командами и чёткими конкурентными преимуществами.',
    strategy_risk_title: 'Управление рисками',
    strategy_risk_desc: 'Диверсификация портфеля по секторам и географии ограничивает концентрационный риск. Активное участие в советах директоров, регулярный мониторинг и структурированные контрольные точки обеспечивают раннее выявление и снижение рисков.',
    strategy_value_title: 'Создание стоимости',
    strategy_value_desc: 'Помимо капитала, мы обеспечиваем операционную поддержку: стратегии выхода на глобальные рынки, доступ к сети руководителей, юридическое и регуляторное сопровождение, оптимизацию выручки и подготовку к листингу. Наш подход "умных денег" обеспечил средний рост капитализации 10×.',

    // About
    about_label: 'О нас',
    about_title: 'Simplex Capital Международный фонд',
    about_desc: 'Первоклассный институциональный инструмент для стратегических технологических инвестиций на российских и глобальных рынках.',
    about_fund_label: 'Структура фонда',
    about_fund_title: 'Институциональный фундамент',
    about_fund_desc: 'Структурированный как партнёрство с ограниченной ответственностью, зарегистрированное на Каймановых островах, наш фонд придерживается высочайших стандартов институционального управления и прозрачности.',
    about_spec_size: 'Целевой размер фонда',
    about_spec_term: 'Срок фонда',
    about_spec_mgmt: 'Комиссия за управление',
    about_spec_carry: 'Доля в прибыли',
    about_spec_return: 'Целевая чистая доходность',
    about_spec_hurdle: 'Пороговая ставка',

    // Portfolio
    portfolio_label: 'Портфель',
    portfolio_title: 'Подтверждённый опыт',
    portfolio_desc: 'История успешных инвестиций в быстрорастущие технологические компании международных рынков.',

    portfolio_cat_social: 'Социальные сети / Платформы',
    portfolio_cat_nano: 'Нанотехнологии',
    portfolio_cat_it: 'IT-услуги',
    portfolio_cat_dist: 'IT-дистрибуция',
    portfolio_cat_mobility: 'Мобильность / On-Demand',
    portfolio_cat_telecom: 'Телеком / Цифровые технологии',
    portfolio_cat_media: 'Медиа / Tech',
    portfolio_detail_vk: 'Крупнейшая социальная сеть России и СНГ с более чем 100 млн ежемесячных пользователей. Многофункциональная цифровая экосистема.',
    portfolio_detail_ocsia: 'Люксембургская нанотехнологическая компания и крупнейший в мире промышленный производитель графеновых нанотрубок (одностенных углеродных нанотрубок).',
    portfolio_detail_epam: 'Листинг на NYSE. Мировой лидер в инжиниринге цифровых платформ и разработке ПО с выручкой свыше $4 млрд.',
    portfolio_detail_softline: 'IPO на Лондонской фондовой бирже. Ведущий глобальный поставщик IT-решений и услуг в более чем 50 странах.',
    portfolio_detail_dataart: 'Международный технологический консалтинг с более чем 6 000 специалистов. Место в совете директоров и рост капитализации в 10×.',
    portfolio_detail_gett: 'Ведущая платформа корпоративного транспорта, работающая на крупных международных рынках.',
    portfolio_detail_mts: 'Крупнейший мобильный оператор России с масштабной цифровой экосистемой. Листинг на NYSE и MOEX.',
    portfolio_detail_nmg: 'Крупнейший частный медиахолдинг России с обширными цифровыми и вещательными активами.',
    portfolio_patterns_label: 'Ключевые закономерности в технологиях',
    portfolio_pattern1_title: 'Глобальное мышление с первого дня',
    portfolio_pattern1_desc: 'Основатели технологических компаний из России всё чаще строят бизнес с прицелом на глобальные рынки с самого начала.',
    portfolio_pattern2_title: 'Сильная техническая база',
    portfolio_pattern2_desc: 'Мировой уровень инженерных команд с глубокой экспертизой в области ИИ, кибербезопасности и корпоративного ПО.',
    portfolio_pattern3_title: 'Исключительные команды и эффективные бизнес-модели',
    portfolio_pattern3_desc: 'Мы сотрудничаем с первоклассными командами основателей и делаем ставку на операционно эффективные, масштабируемые бизнес-модели с четким, ограниченным по срокам путем к прибыльности.',

    // Team
    team_label: 'Команда',
    team_title: 'Опыт команды',

    // Pipeline
    pipeline_label: 'Сделки',
    pipeline_title: 'Инвестиционный пайплайн',
    pipeline_desc: 'Текущие возможности, находящиеся на рассмотрении по целевым секторам.',

    // Insights
    insights_label: 'Аналитика рынка',
    insights_title: 'Технологии превосходят все классы активов',
    insights_desc: 'Аналитика, подтверждающая нашу инвестиционную тезу о превосходящей доходности технологических инвестиций.',

    // For Investors
    investors_label: 'Инвесторам',
    investors_title: 'Портал инвестора',
    investors_desc: 'Всё необходимое для оценки и участия в фонде Simplex Capital.',

    // Contact
    contact_label: 'Контакты',
    contact_title: 'Свяжитесь с нами',
    contact_desc: 'Обратитесь к нашей команде по работе с инвесторами, чтобы узнать больше об инвестициях с Simplex Capital.',
    contact_name: 'Полное имя',
    contact_email: 'Электронная почта',
    contact_phone: 'Номер телефона',
    contact_type: 'Тип инвестора',
    contact_message: 'Сообщение',
    contact_submit: 'Отправить запрос',
    contact_success: 'Спасибо за ваш запрос. Мы свяжемся с вами в ближайшее время.',

    // Footer
    footer_disclaimer: 'Прошлые результаты не являются гарантией будущих. Инвестиции в фонды прямых инвестиций сопряжены со значительным риском, включая возможную потерю основного капитала. Данный сайт носит исключительно информационный характер и не является предложением о продаже или покупке ценных бумаг.',
    footer_fund: 'Фонд',
    footer_investors: 'Инвесторам',
    footer_rights: 'Все права защищены.',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');
  const t = (key) => translations[lang][key] || translations['en'][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}